{{- with .Values.apigatewayservice.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.apigatewayservice.secretName }}
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}